### ISSUE TITLE
ObfuscateEmailAddressMiddleware does not use ROT13 encoding

### ISSUE THREAD

**Issue by jaap3** [leukeleu/wagtail-extras#1]
In the README it's claimed that the "ObfuscateEmailAddressMiddleware transforms emailaddresses to ROT13-encoded strings". This is not true at all. 

The only thing that happens is that email address are transformed to decimal/hexadecimal unicode character entities. i.e. `'foo@bar.com'` is transformed to `'&#102;&#111;&#x6f;&#x40;&#x65;&#x78;&#97;&#x6d;&#x70;&#x6c;&#x65;&#46;&#99;&#x6f;&#x6d;'` (or a variation thereof, the choice of decimal/hexadecimal reference is randomized).

This is easily decoded by any tool that's able to parse HTML (i.e. your browser):

```
var p = document.createElement('p'); 
p.innerHTML = '&#102;&#111;&#x6f;&#x40;&#x65;&#x78;&#97;&#x6d;&#x70;&#x6c;&#x65;&#46;&#99;&#x6f;&#x6d;'; 
p.textContent // foo@bar.com
```

**Comment by ramonakira** [comment]
Thanks, I have adjusted the readme.md
